# minio配置 文件上传使用
minio:
  endpoint: ${com.hotsharp.minio.endpoint}
  accessKey: ${com.hotsharp.minio.accessKey}
  secretKey: ${com.hotsharp.minio.secretKey}
  bucket: ${com.hotsharp.minio.bucket}
ffmpeg:
  path: ${FFMPEG_PATH:ffmpeg}
# 文件路径
file:
  video:
    tmp: ${VIDEO_TMP:video/tmp/}
    m3u8: ${VIDEO_M3U8:video/m3u8/}
# spring配置
spring:
  application:
    name: video-service
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: -1
  datasource:
    url: jdbc:mysql://${hotsharp.db.motisja.host}:3306/hottube?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: ${hotsharp.db.motisja.pw}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        namespace: ${hotsharp.nacos.namespace}
# 服务配置
server:
  port: ${SERVER_PORT:40006}
# mp 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    auto-mapping-behavior: partial # 默认值 非嵌套的自动映射
  mapper-locations: classpath:/mapper/**.xml
  type-aliases-package: com.hotsharp.pojo.entity