com:
  hotsharp:
    minio:
      endpoint: http://47.121.126.119:9090/
      accessKey: dBx9QNbiq9ztwqRChXXO
      secretKey: jeC6bk0rCHyFWn08uKUxSp2cVaAG67t2Jkkc5nqP
      bucket: hottube
    mysql:
      host: 47.121.126.119
      port: 3307
      db: hot-tube
      username: root
      passwd: hottube123
    redis:
      host: 47.121.126.119
      port: 6379
      passwd: 250@wangqiang