# minio配置 文件上传使用
minio:
  endpoint: ${MINIO_ENDPOINT}
  accessKey: ${MINIO_ASSESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET:hottube}
ffmpeg:
  path: ${FFMPEG_PATH:ffmpeg}
# 文件路径
file:
  video:
    tmp: ${VIDEO_TMP:video/tmp/}
    m3u8: ${VIDEO_M3U8:video/m3u8/}
# spring配置
spring:
  application:
    name: video-process
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: -1
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWD}
      timeout: 6000ms
# 服务配置
server:
  port: ${SERVER_PORT:8090}
# mp 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  #    auto-mapping-behavior: partial # 默认值 非嵌套的自动映射
  mapper-locations: classpath:/mapper/**.xml
  type-aliases-package: com.tube.pojo.entity