server:
  port: 40000
spring:
  datasource:
    url: jdbc:mysql://${hotsharp.db.host}:3306/hottube?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hotsharp.db.pw}
hottube:
  jwt:
    location: classpath:hottube.jks
    alias: hottube
    password: hottube123
    tokenTTL: 30m
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
api-docs:
  path: v3/api-docs # 指定生成文档的路径，网关会访问这个路径来拉取文档
group-configs:
  - group: 'default'
    paths-to-match: '/**'
    packages-to-scan: com.hotsharp.auth.controller # 指定要扫描的包
knife4j:
  enable: true  # 开启knife4j接口文档美化
  setting:
    language: zh_cn # 指定语言