server:
  port: 50000
spring:
  application:
    name: user-service # 微服务名称
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${hotsharp.db.host}:3306/hm-user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hotsharp.db.pw}
  cloud:
    nacos:
      server-addr: 172.31.170.153:8848
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.hotsharp: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    title: HotTube用户服务接口文档
    description: "HotTube用户服务接口文档"
    email: hmotisja@gmail.com
    concat: MotisJA
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.hmall.user.controller
hottube:
  jwt:
    location: classpath:hottube.jks
    alias: hottube
    password: hottube123
    tokenTTL: 30m