server:
  port: 50001
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 172.31.170.153:8848
    gateway:
      routes:
        - id: user # 路由规则id，自定义，唯一
          uri: lb://user-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/users/** # 这里是以请求路径作为判断规则
hottube:
  jwt:
    location: classpath:hottube.jks
    alias: hottube
    password: hottube123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /users/register
