server:
  port: 50000
  tomcat:
    connection-timeout: 10000
spring:
  cloud:
    nacos:
      discovery:
        namespace: ${hotsharp.nacos.namespace}
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#        httpclient:
#          pool:
#            type: fixed
#            maxIdleTime: 10000
#            max-connections: 200
#            acquire-timeout: 45000
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
#knife4j:
#  gateway:
#    enabled: true
#    strategy: discover
#    discover:  # 开启服务发现，启动之后就会自动聚合在注册中心注册的所有微服务文档了
#      enabled: true
#      version: openapi3
#      excluded-services:
#        - gateway-service

#knife4j:
#  # 聚合swagger文档
#  gateway:
#    enabled: true
#    # 排序规则(tag/operation排序自4.2.0版本新增)
#    # 取值：alpha-默认排序规则，官方swagger-ui默认实现,order-Knife4j提供的增强排序规则，开发者可扩展x-order，根据数值来自定义排序
#    tags-sorter: order
#    operations-sorter: order
#    # 指定手动配置的模式(默认为该模式)
#    strategy: manual
#    routes:
#      - name: 用户服务
#        # 真实子服务访问url地址-提供OpenAPI的文档
#        url: /user-service/v3/api-docs?group=default
#        service-name: user-service
#        # 路由前缀
#        # 兼容OpenAPI3规范在聚合时丢失contextPath属性的异常情况，由开发者自己配置contextPath,Knife4j的前端Ui做兼容处理,与url属性独立不冲突，仅OpenAPI3规范聚合需要，OpenAPI2规范不需要设置此属性,默认为(apiPathPrefix)
#        context-path: /
#        order: 2
hottube:
  jwt:
    location: classpath:hottube.jks
    alias: hottube
    password: hottube123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /auth/account/register
      - /auth/account/login
      - /swagger-ui/**
      - /v3/api-docs/**
      - /doc.html
      - /webjars/**
      - /druid/**
      - /favicon.ico
      - /video/category/getall
      - /video/random/visitor
      - /video/cumulative/visitor
      - /video/getone
      - /msg/chat/outline
      - /video/play/visitor
      - /favorite/get-all/visitor
      - /search/**
      - /comment/get
      - /comment/reply/get-more
      - /comment/get-up-like
      - /user/info/get-one
      - /video/user-works-count
      - /video/user-works
      - /favorite/video/user-love
      - /favorite/video/user-collect
      - /relation/followed/**
      - /relation/follower/**


