hotsharp:
  db:
    motisja:
      host: 49.235.47.8
      pw: admin@motisja466
  redis:
    host: 47.121.126.119
    pw: 250@wangqiang
  nacos:
    namespace: b62f0c48-d9bd-4496-aaf4-4f380dfbe1ee
#    namespace: 946e537a-6d45-40a8-9c14-de7114f247f1
  elasticsearch:
    host: 172.31.170.153
    port: 9200

feign:
  okhttp:
    enabled: true # 开启OKHttp功能
